# Generated by Django 5.0.6 on 2024-06-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cascadeAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='security_answer_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='security_question_2',
        ),
    ]
