# Generated by Django 5.0.6 on 2024-07-03 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cascadeAuth', '0002_remove_userprofile_security_answer_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='security_answer_2',
            field=models.CharField(default='default_answer', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_answer_3',
            field=models.CharField(default='default_answer', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_question_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_question_2', to='cascadeAuth.securityquestion'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_question_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_question_3', to='cascadeAuth.securityquestion'),
        ),
    ]
