# Generated by Django 5.0.6 on 2024-07-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cascadeAuth', '0004_remove_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
